### ISSUE TITLE
split the file into chunks

### ISSUE THREAD

**Issue by obvioussea** [TomFrankly/pipedream-notion-voice-notes#11]
Hello, I have a problem with Notion, I used the dropbox version and when I run the test it gives me this error:

An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI: undefined Connection error.

![Screenshot 2023-09-26 111522](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/89933441/de2e5240-b5d2-4bef-b7ef-0e57312eb276)

The script get triggered when I upload something but at the end it doesn't work

**Comment by obvioussea** [comment]
I want to add that I have a free account for everything, can it be a problem?

free dropbox, notion and open AI

thanks

**Comment by TomFrankly** [comment]
Is your OpenAI API key valid still? And if you haven't set up billing info with OpenAI, are you sure you still have valid trial credit? (It expires after 3 months).

If not, you can add your billing info and then create a new API key, setting it in the workflow settings.

Note that you don't need ChatGPT Plus for this; you just need billing info set for API use.
