### ISSUE TITLE
Type Error  Cannot read properties of undefined (reading 'select')

### ISSUE THREAD

**Issue by macasas** [TomFrankly/pipedream-notion-voice-notes#12]
When i select the Notion Notes Database i get

Type Error
Cannot read properties of undefined (reading 'select')

Does this mean my Notions Note database has the wrong properties, I have tried to match the property names to those shown in the flow, but I have probably missed one as this is not clear.

Or is there another cause for this?

I see you have had similar messages reading 'map' and reading 'include' is this one related?

**Comment by TomFrankly** [comment]
That happens after you select the Notion database, not when trying to select other properties?

And you're able to successfully see your Notion databases and click one?

If so, can you share a list of the properties in your database?

The only instance of the `select` keyword I see in the entire script is:

```
noteTag: {
				type: "string",
				label: "Note Tag",
				description:
					'Choose a Select-type property for tagging your note (e.g. tagging it as "AI Transcription").',
				options: selectProps.map((prop) => ({ label: prop, value: prop })),
				optional: true,
				reloadProps: true,
			},
			...(this.noteTag && {
				noteTagValue: {
					type: "string",
					label: "Note Tag Value",
					description: "Choose the value for your note tag.",
					options: this.noteTag
						? properties[this.noteTag].select.options.map((option) => ({
								label: option.name,
								value: option.name,
						  }))
						: [],
					default: "AI Transcription",
					optional: true,
				},
			})
```

So it should only become relevant if you've already chosen a Note Tag property.

**Comment by macasas** [comment]
Hi

The first run through a new pipeline allows me to select the database, then Title, Duration and Cost but it does not show any properties in the Tag field.  I tried adding a single and multi tag field, but no property names appear for Tag.

But I open the field trying to select something, add a custom or whatever and then the error appears.  Once it has appeared, no amount of clearing, reset, page resetting makes any difference, I have to delete the pipeline and create another, but Tag never shows any properties to select so I cannot get past this point.

**Comment by macasas** [comment]
I have just tried it again after reading your code snippet, and created a multi select with AI Transcription as an option, as well as a single select with AI Transcription, and this time the Single Select appeared in the list.  The property was there before, but not the option.

The pipeline is now reaching the end, fills Title, Duration, Cost and Tag but I don't get transcription, summary or any of the others, so will go take a look at what I am supposed to be calling those properties, I just copied the names.  I know I should use your brain database, but your brain looks complicated and as I brand new to notion I'm not even sure what I can do yet, so this will be my introduction and if I can start creating notes while walking I'm sure the rest will follow.  Thanks for your hard work.

**Comment by macasas** [comment]
Okay, I am now running although despite reading and watching, I still don't understand where the actual page is being created because I get a listing, but was expecting a page to be displayed underneath it somehow.  I'm sure the notion of Notion will come.  Do you have a video explaining how the database hides the page?

This is not really an issue, but more a bit of tidying up in your code. That is some work of art you have created, and in a single file.

In the prompt you have a section
`You only write valid JSON.${languagePrefix}`
And when `languagePrefix` is undefined, as it is in mine, the prompt says
`You only write valid JSON.undefined`

It doesn't effect the result much because you repeat the same command about responding in only json elsewhere, but just thought you might like to tidy it with a default value or something.

Thanks again.  Time to go play.

**Comment by TomFrankly** [comment]
D'oh! I didn't know that template literals would convert `undefined` variables to the string value "undefined". I thought it would just skip over it. Time to refactor that part of the prompt constructor!

I'll take a look at the code for the Note Tag property as well.

Are you able to continue using the workflow if you just don't set a Note Tag property? You don't actually need one to use the workflow - I've tested this on a totally-new database with no properties other than the default Name property, and it works fine.

If you're still not getting the transcript, can you paste the contents of your Logs tab here?

**Comment by macasas** [comment]
The Note Tag property needed to be of type Single Select, with the AI Transcription option entered into the database, then it showed up in the list to be selected.

When the fields were not selecting properties the option to save the pipeline was disabled, so not sure how you would use an empty database.

Anyway, it is now running and I will be trying it out on my walk today, no more excuses :-)

**Comment by macasas** [comment]
I managed to record 5 notes while walking.  All of them uploaded fine to Google Drive

The first one failed with an error

Cannot read properties of undefined (reading 'toLowerCase') 
    at null.null (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1071:63)
    at Array.map (null:null:null)
    at Object.formatChat (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1071:44)
    at Object.run (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1928:40)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)
which appears to be the Related Topics section, 

           ...(this.summary_options.includes("Related Topics") &&
                    chatResponse.related_topics.length > 1 && {
                        related_topics: Array.from(
                            new Set(
                                chatResponse.related_topics.flat().map((item) => item.toLowerCase())
                            )
                        ).sort(),
                    }),

so not sure why ‘item’ would be undefined here.  All I can say is it was my first try in the wild, it was fairly long 21:14 21.3Mb and there were some points with loud road noise and machinery.


The next 3 worked fine and added notes as expected.

The last recording failed on a moderation check, and its done this twice now whenever mentioning anything to do with health.  I stated a medical fact, it claims this is “inappropriate”

Who is doing the moderation?  Is it you before it gets sent, or is it sent to chatgpt to be moderated.  Seems to me, chatgpt is suppressing perfectly normal content that people might want to talk and write about.

**Comment by TomFrankly** [comment]
Yeah, moderation is turning out to be problematic. It's flagging way more aggressively for other people than it did for me, and OpenAI also seems to have added tight rate-limiting to it in the last few days. I'm shipping an update that will disable it by default.

**Comment by macasas** [comment]
Yeah I agree, I've been reading about people using chatgpt to go through medical school and do medical research, and I literally mentioned the word doctor twice and it rejected me :-). Would it not be possible to just reject that chunk, and substitute it with a warning message, rather than the whole recording?  

This is such a fluid space at the moment I would think extracting as many variables as possible would make things more robust for you, because its sometimes hard to keep up with these well resourced companies.

Also, not sure this is the place, but wondering how much effort it would be to extract out sections of the prompt so your script could be used to do other things, not just make notes?  I'm looking to make different recordings for different purposes, move them into different Drive folders and run different prompts on them.

Your script is still great to play with, even if a few don't get through :-)

**Comment by TomFrankly** [comment]
Rejecting a specific chunk would be a "quiet failure", which I want to avoid as much as possible. But there are probably more refined ways of doing moderation. The endpoint returns a `flagged` boolean value, which is what I currently check. But it also returns scores for different categories (violence, abuse, etc), so it might be better to define thresholds for each category.

That said, I've read something about the moderation endpoint not being as smart as ChatGPT anyway, so maybe it's not worth the hassle right now. This is a Bring-Your-Own-Key workflow. so to a certain degree it's up to the user to be responsible with the kind of content they submit.

As for your other question - right now it'd be pretty pretty hard unless you understand the Pipedream CLI well. However, the foundation is there for a lot more flexibility.

My team and I will be implementing this workflow into our upcoming app, and we're getting close enough to launch that I feel comfortable sharing the landing page: https://flylighter.com/

I still need to add a better confirmation page after waitlist signup - I'll be adding that later today!

We're launching primarily as a web clipper first, but part of the reason I've been building all these Pipedream workflows is to give our team a head start in adding voice-recording and AI summarization features.
