### ISSUE TITLE
How do I resolve this error?

### ISSUE THREAD

**Issue by Dbaileyicd10** [TomFrankly/pipedream-notion-voice-notes#15]
Error
Failed to download file: Missing `url` property 
    at Object.downloadToTmp (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:304:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///pipedream/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1843:5)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)
(notion_voice_notes)

**Comment by Dbaileyicd10** [comment]
Message:
Failed to download file: Missing `url` property
Total Duration:
13,060 ms
Compute Time:
12,756 ms
Execution Start:
2023-09-26T17:07:32.720Z
Execution End:
2023-09-26T17:07:45.780Z
Steps Executed:
1 / 1
Credits:
1
Version:
28 (d_n3sxBGqn)

**Comment by Dbaileyicd10** [comment]
Inputs

Logs
steps.trigger
{2}
context
{15}
deployment_id:
d_n3sxBGqn
hops:
null
id:
2VwXKXF2tXiX6HYmiCZDCJVLZXs
owner_id:
o_5kI0r5g
pipeline_id:
null
platform_version:
3.42.2
replay:
false
resume:
null
source_type:
COMPONENT
test:
false
trace_id:
2VwXKTyXXG4xnyXNO1EsAZhIOPP
ts:
2023-09-26T17:07:32.702Z
verified:
false
workflow_id:
p_dDCpwLA
workflow_name:
Notion Voice Notes (Dropbox)
event
{11}
.tag:
file
client_modified:
2023-09-26T17:07:28Z
content_hash:
098c4b0113d9c70640585a1444317881ee62b36be58479927c4765d7ac7136ce
id:
id:ulK99M3YCvQAAAAAAAAbhw
is_downloadable:
true
name:
Dusty Preaching.m4a
path_display:
/Audio Files/Dusty Preaching.m4a
path_lower:
/audio files/dusty preaching.m4a
rev:
606461c0e7bfa04b5838a
server_modified:
2023-09-26T17:07:28Z
size:
25932146

**Comment by Dbaileyicd10** [comment]
Notion Account:
dbaileyicd10@gmail.com
OpenAI (ChatGPT) Account:
OpenAI (ChatGPT) #1
Previous Step Data (Set By Default):
{ "trigger": { "event": { ".tag": "file", "name": "Dusty Preaching.m4a", "path_lower": "/audio files/dusty preaching.m4a", "path_display": "/Audio Files/Dusty Preaching.m4a", "id": "id:ulK99M3YCvQAAAAAAAAbhw", "client_modified": "2023-09-26T17:07:28Z", "server_modified": "2023-09-26T17:07:28Z", "rev": "606461c0e7bfa04b5838a", "size": 25932146, "is_downloadable": true, "content_hash": "098c4b0113d9c70640585a1444317881ee62b36be58479927c4765d7ac7136ce" }, "context": { "id": "2VwXKXF2tXiX6HYmiCZDCJVLZXs", "ts": "2023-09-26T17:07:32.702Z", "pipeline_id": null, "workflow_id": "p_dDCpwLA", "deployment_id": "d_n3sxBGqn", "source_type": "COMPONENT", "verified": false, "hops": null, "test": false, "replay": false, "owner_id": "o_5kI0r5g", "platform_version": "3.42.2", "workflow_name": "Notion Voice Notes (Dropbox)", "resume": null, "trace_id": "2VwXKTyXXG4xnyXNO1EsAZhIOPP", "attachments": {} } } }
Summary Options:
[ "Summary", "Main Points", "Action Items", "Follow-up Questions", "Sentiment", "Related Topics", "Arguments", "References", "Stories" ]
Notes Database:
Notes (7563d44e-4bf9-4fc1-aa47-b9471478d824)
Note Title (Required):
Name
Note Duration:
-
Note Cost:
Transciption Cost
Note Tag:
-
ChatGPT Model:
gpt-3.5-turbo
Transcript Language (Optional):
-
Enable Advanced Options:
true
Summary Density (Advanced):
2750
Summary Verbosity (Advanced):
High
Summary Language (Advanced):
-
Model Temperature:
-
Audio File Chunk Size:
24
Disable Moderation Check:
true

**Comment by TomFrankly** [comment]
Was this a Dropbox file? If so, can you try reuploading (change the file name slightly so it's new) and testing that through the workflow?

Dropbox download links expire after a while, so if you spent some time setting up the workflow after uploading, this can happen.

**Comment by TomFrankly** [comment]
Gotcha.

When you do, can you check to make sure that Include Link is set to True?

That error happens if the 'link' property isn't present in the trigger's export:

![CleanShot 2023-09-26 at 11 36 48@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/85b45f55-0b60-4c91-a4d0-af7af1f86c6a)

**Comment by Dbaileyicd10** [comment]
This is the error message I got this time.


[A screenshot of a computer  Description automatically generated]

**Comment by TomFrankly** [comment]
Gotcha, I think that might have to do with the Related Topics option, though I'm not quite sure why yet. For now, I think if you uncheck Related Topics in the Summary Options, you should bypass this error.

**Comment by Dbaileyicd10** [comment]
That fixed it.  Thank you so very much

**Comment by TomFrankly** [comment]
I've just shipped a new version that should completely fix this error, and allow you to re-enable Related Topics if you want.

Here are the release notes for the newest version: https://github.com/TomFrankly/pipedream-notion-voice-notes/releases/tag/v0.7.0
