### ISSUE TITLE
Throw Error Bug: not throwing the actual error

### ISSUE THREAD

**Issue by sudo-eugene** [TomFrankly/pipedream-notion-voice-notes#17]
Hey @TomFrankly 

This is absolutely insane, thanks for building this!

This is not a critical bug, but it seems like the error from the code is not being logged in pipedream. The expected behaviour would have been to see 'Unsupported file type. Only mp3 and m4a files are supported." in Pipedream.

<img width="886" alt="Screenshot 2023-09-27 at 08 51 33" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/145440622/a0a8f3bb-773c-4799-9f5e-71b773d76e71">

<img width="886" alt="Screenshot 2023-09-27 at 08 51 27" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/145440622/cca1d67e-efe0-4873-9f60-1c994464c4b9">

Nonetheless, when I changed to mp3/m4a it worked.

**Comment by sudo-eugene** [comment]
@TomFrankly I tried my luck with a .mp4 recording from Google Meet - which will be a game-changer for me and our team's meetings!

**Comment by TomFrankly** [comment]
@sudo-eugene just shipped an update with .mp4 support, although I'm still limiting the file size to 200mb for now. I'll work on increasing that in the near future.

Here are the release notes for the newest version: https://github.com/TomFrankly/pipedream-notion-voice-notes/releases/tag/v0.7.0

**Comment by TomFrankly** [comment]
@sudo-eugene it's possible that a separate workflow would work for this. I tried writing a converter (m4a to mp3), but on Pipedream the conversion process was taking 4+ minutes even for a small file.

The same conversion happens really quickly on my Macbook, so there must be something about how ffmpeg runs on AWS Lambda that makes file-type conversion really slow. That's the only reason I haven't shipped conversion code in my workflow!

Another option, if you use Dropbox, is to use their folder automations to convert the file when it's uploaded.
