### ISSUE TITLE
Consistent Error Invalid duration number (thrown from calculateTranscriptCost).

### ISSUE THREAD

**Issue by weslo83** [TomFrankly/pipedream-notion-voice-notes#22]
![Screenshot 2023-09-30 145633](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146588741/5c9ba02c-2175-4a71-b84d-931d13ef53bf)

Invalid duration number (thrown from calculateTranscriptCost).

I keep getting this error

**Comment by TomFrankly** [comment]
@weslo83 did this get fixed for you?

**Comment by weslo83** [comment]
Yes sir. I started using a different voice recording app.

**Comment by TomFrankly** [comment]
Gotcha, glad you were able to get that figured out!

I experimented a bit over the weekend with building an mp3 conversion fallback into the script, but for some reason Pipedream just can't seem to do it before I hit the timeout limit. Oddly, conversion from m4a to mp3 chunks happens quite quickly on my Macbook, and only takes slightly longer than simply chunking the files into the same format as the original file.

So there's something as-of-yet-undiscovered in Pipedream or AWS Lambda that's having issues with conversion specifically.
