### ISSUE TITLE
Failed to download file: Cannot read properties of undefined (reading 'match')

### ISSUE THREAD

**Issue by bobbymahmood** [TomFrankly/pipedream-notion-voice-notes#23]
I'm attempting this with an MP4 file. Will it work with other file types or just MP3?

This is the error message:
Error
Failed to download file: Cannot read properties of undefined (reading 'match')

DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:304:11)
    at Object.run (file:///tmp/__pdg__/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1843:16)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

Under Logs I see:

01/10/2023, 17:38:28
Checking that file is under 300mb...

01/10/2023, 17:38:28
File size is approximately 75.5mb.

01/10/2023, 17:38:28
File is under the size limit. Continuing...

01/10/2023, 17:38:28
Checking if the user set languages...

01/10/2023, 17:38:28
No language set. Whisper will attempt to detect the language.

**Comment by TomFrankly** [comment]
Hey @bobbymahmood - I've just updated the workflow to support .mp4 files as well, up to 200mb.

Keep in mind that .mp3 files are still the best kind of file to upload. In future releases, I'll work on increasing the file size limit.

Here are the release notes for the newest version! https://github.com/TomFrankly/pipedream-notion-voice-notes/releases/tag/v0.7.0

**Comment by bobbymahmood** [comment]
Ok thanks, so this still didn't work for me, I got the error  Cannot read
properties of null (reading '0')

But I was able to convert the video file to MP3, its a manual step for me,
but it worked perfectly when once I had converted to audio. Thanks!
