### ISSUE TITLE
Execution times out

### ISSUE THREAD

**Issue by brudjones** [TomFrankly/pipedream-notion-voice-notes#24]
I got this error today while trying to process a file.  Is it something that subscribing to chat gpt4 would help with?
the file is less than 15mb
![6EA33E85-D033-4A45-8FA0-D2611F5BB697](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146113733/f12da513-2ac3-4f12-89b7-0754fd74924c)
![3222A2C3-DE02-4CFE-A3E5-381CA5D44E2F](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146113733/6a19dfe0-3bbe-451a-9231-83253e94b611)

**Comment by TomFrankly** [comment]
This error indicates that the workflow timed out before it could finish. By default, I set the timeout for this workflow at 5 minutes, which is the highest it can go on Pipedream's free account. You can go into the Settings for the workflow and set it as high as 12.5 minutes if you're on a paid plan.

However, 15mb indicates that the file isn't very long, so it might be that something got stuck on OpenAI's end or on Notion's end. I'd suspect Notion, as they've been having API issues today. I've successfully processed files over 100mb and over 3 hours long within the 5-minute timeout limit.

You can check the Logs tab to see how far through the process the script got before timing out. After that, I'd recommend trying again.

And no, you don't need to subscribe to ChatGPT Plus! Doing so would not change anything, as this workflow uses the pay-as-you-go OpenAI APIs, which are totally separate from ChatGPT Plus.

Additionally, GPT-4 is a slower model than gpt-3.5-turbo, so switching to it would likely just make things even more likely to time out.

**Comment by brudjones** [comment]
I will retry the file later to see if its an API issue

attached is the log as well
![6DAE897F-A077-42D3-9EDF-0C31A400BDEC](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146113733/1446b0c8-d60a-4f63-894c-5d6297be4790)

**Comment by TomFrankly** [comment]
Ok, looks like it chunked the file successfully, but timed out before it ever got a response from OpenAI.

The file is extremely small for being 82 minutes long. Is the quality ok? Perhaps Whisper is having trouble with it.

**Comment by brudjones** [comment]
The audio is good and clear, resaved the file. it is getting farther now but still looks like it fails
![DB853CDE-3C3E-4877-B69F-43186B7D6000](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/146113733/19a9fac3-d4be-47f6-8efd-4859a6f5095b)

**Comment by TomFrankly** [comment]
From these logs, we can see that it took nearly 4 minutes just to transcribe the file.

What did you use to create this file? Again, 15mb for an 82-minute file is very uncommon. Is the bitrate very low?

One thing you can do is Enable Advanced Settings and then set Audio File Chunk Size to 8. That should just about double the speed of transcription.

But this is an odd edge case where the audio file is very long, resulting in a lengthy transcription time, but it's not very big, meaning we can't split it into lots of little chunks and use concurrent requests to transcribe them all at the same time.

It's only with the current code we can only split it into 2 chunks.
