### ISSUE TITLE
undefined Connection error.

### ISSUE THREAD

**Issue by KnDuyHul** [TomFrankly/pipedream-notion-voice-notes#25]
I am getting this issue:  It charged my account 30cents, but no notion note??

An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: undefined Connection error.

**Comment by TomFrankly** [comment]
Are you using trial credit, or did you create your API key after entering billing info?

Since it's "unidentified connection error" this error is very hard to debug. But some folks have reported getting past it after following the directions I wrote in the custom error message.

**Comment by KnDuyHul** [comment]
NEvermind, I got it now... BTW THANK YOU SOOOOO MUCH for this amazing open free code! The world needs more of you!

**Comment by TomFrankly** [comment]
@KnDuyHul was adding billing into and making a new key the fix?

If so, I can add it as an official fix in the FAQ section of the article :)
