### ISSUE TITLE
Error: Failed to create Notion page.

### ISSUE THREAD

**Issue by xandraaling** [TomFrankly/pipedream-notion-voice-notes#27]
I tested the Notion Voice Notes (Dropbox) automation and it worked. However, I tried to add a file to my Dropbox folder and got this error code. Can someone help?
<img width="802" alt="Screenshot 2023-10-08 at 6 40 49 PM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/147350963/3f04f048-10a9-49cd-9975-45cc036363ee">

**Comment by TomFrankly** [comment]
@xandraaling could you post a screenshot of your Logs tab on that run, making sure to include the bits at the bottom?

Also, have you tried this again with a different audio file?

It's likely a Notion API issue, and might be worked out by trying again.

**Comment by TomFrankly** [comment]
This seems to be the crux of the issue:

![CleanShot 2023-10-09 at 10 14 02@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/98f26b37-4b55-4ad9-a6ee-f34367f14807)

It's saying "Duration is not a property that exists".

This is a bit odd, as the Duration field should only let you pick an existing property. Did you perhaps pick a property, then delete it in Notion?

In any case, if you clear that property in the Pipedream settings, things should work.
