### ISSUE TITLE
This voice notes app does not work for me

### ISSUE THREAD

**Issue by frjohn284** [TomFrankly/pipedream-notion-voice-notes#28]
code does not work>

Checking that file is under 300mb...

10/12/2023, 4:20:12 PM
File size is approximately 6.1mb.

10/12/2023, 4:20:12 PM
File is under the size limit. Continuing...

10/12/2023, 4:20:12 PM
Checking if the user set languages...

10/12/2023, 4:20:12 PM
No language set. Whisper will attempt to detect the language.

10/12/2023, 4:20:13 PM
Downloaded file to tmp storage:

10/12/2023, 4:20:13 PM
{ path: '/tmp/sample audio file.mp3', mime: '.mp3' }

10/12/2023, 4:20:13 PM
Successfully got duration: 256 seconds

10/12/2023, 4:20:13 PM
Chunking file: /tmp/sample audio file.mp3

10/12/2023, 4:20:13 PM
Chunks created successfully. Transcribing chunks: chunk-000.mp3

10/12/2023, 4:20:13 PM
Transcribing file: chunk-000.mp3

Copy
10/12/2023, 4:21:34 PM
Attempting to clean up the /tmp/ directory...

10/12/2023, 4:21:34 PM
Cleaning up /tmp/chunks-2WgLJRUbTr79DBocboXgkaKrmui...

10/12/2023, 4:21:34 PM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by frjohn284** [comment]
I get the same error regardless of which drive i use: google, dropbox etc.
Is it possible that this is related to Notion? I set up notion as a 'student' this appears to be a bad idea.

   An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: undefined Connection error.

DETAILS
    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

and this

Checking that file is under 300mb...

10/13/2023, 12:19:24 PM
File size is approximately 6.1mb.

10/13/2023, 12:19:24 PM
File is under the size limit. Continuing...

10/13/2023, 12:19:24 PM
Checking if the user set languages...

10/13/2023, 12:19:24 PM
No language set. Whisper will attempt to detect the language.

10/13/2023, 12:19:24 PM
Successfully got duration: 256 seconds

10/13/2023, 12:19:24 PM
Chunking file: /tmp/Sample Audio File4.mp3

10/13/2023, 12:19:24 PM
Chunks created successfully. Transcribing chunks: chunk-000.mp3


Copy
10/13/2023, 12:19:24 PM
Transcribing file: chunk-000.mp3

10/13/2023, 12:20:46 PM
Attempting to clean up the /tmp/ directory...

10/13/2023, 12:20:46 PM
Cleaning up /tmp/chunks-2Wih9VxXA7NGDq2CClmWPkqCLbp...

10/13/2023, 12:20:46 PM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)

Thanks

**Comment by TomFrankly** [comment]
Hi @frjohn284,

This sound very similar to this issue: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues/11

Try the fix there, and let me know if it doesn't work!

**Comment by frjohn284** [comment]
Thank you. My credit card had been rejected. So new card and new API and works awesome!
