### ISSUE TITLE
Timeout issues on 1h 30min voice recording 

### ISSUE THREAD

**Issue by crypto66699** [TomFrankly/pipedream-notion-voice-notes#33]
TIMEOUT: TIMEOUT
    at Timeout._onTimeout (file:///var/task/lambda_handler.mjs:890:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

**Comment by TomFrankly** [comment]
@crypto66699 if you set Enable Advanced Options to True, you can try setting Summary Density lower and Audio File Chunk Size lower as well.

This will result in smaller, more numerous concurrent requests that should help deal with timeout issues.

I've gotten this workflow to work on a 4-hour file at default settings in the Free plan's 5-minute timeout window, but we're always at the mercy of how fast the OpenAI APIs are running on any given day.
