### ISSUE TITLE
Too much symbols or words to process (on 5 min long audio)

### ISSUE THREAD

**Issue by arefyevandy** [TomFrankly/pipedream-notion-voice-notes#36]
Guys, can you help please?

I receive this error:

body failed validation: body.children[1].paragraph.rich_text[0].text.content.length should be ≤ `2000`, instead was `4492`.

I assume that this means that too much symbols or words (it was a 5 minute audio), because a shorter version was successfull (1 minute).

Help me understand what part of the workflow porvides this limitations and how I can fix them?

**Comment by arefyevandy** [comment]
I have read another issue referring to the same problem - I am using Russian, so the letters are cyrillic

**Comment by arefyevandy** [comment]
I have deployed my pipeline yesterday using instrctions from your manual for Google Drive

Is it using your latest version?

https://github.com/TomFrankly/pipedream-notion-voice-notes/releases/tag/v0.7.0

**Comment by TomFrankly** [comment]
Hey @arefyevandy,

Can you try clicking the Google Drive link here just to make sure you have the latest version? https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow

This _should_ work for cyrillic, but non-English languages do add extra complexity and I've seen other users run into the same body length issue when working outside of English.

I don't have much time at the moment to work on debugging this, but we'll be adding an even better version of this workflow into Flylighter's mobile app once it launches. You can join our waitlist here! https://flylighter.com/

**Comment by arefyevandy** [comment]
Tom,

Thank you for your answer. I highly appreciate your effort to help with
this free product of yours.

Blessings to your path!

------------------------
Андрей Арефьев
 +7 917 578 07 01


чт, 2 нояб. 2023 г. в 02:09, Thomas Frank ***@***.***>:
