### ISSUE TITLE
Customization of Text Options

### ISSUE THREAD

**Issue by EricaVain** [TomFrankly/pipedream-notion-voice-notes#37]
This new method is glorious in it's ease of use and implementation but the lack of tailoring the summary tone and specifics I would like Chatgpt to give me from the transcript makes this version really unusable for me. At the bare minimum I would like to change the 3rd person tone, prompt it for less sterile language as my natural language is more colorful and create lists of points made not constricted to the coded version we have. Is there any way to customize what we are asking Chat GPT to return to us from the transcript besides the provided select-able prompts?

**Comment by TomFrankly** [comment]
This isn't possible right now, but I may be able to add tone controls in a future update. Outputting more lists is a bigger lift, as it involves a lot of code changes in many parts of the workflow.

That said, we'll be adding this workflow into Flylighter's mobile app when it launches, and we'll work to add customization options like this. I have full-time devs working on Flylighter, so we'll be able to put a lot more power into the summarization features. By contrast, this free workflow is just maintained by me, and right now my schedule busy enough that I don't have much time for updates.

If you'd like to join our waitlist, you can do so here! https://flylighter.com/

There's a survey afterward where you're welcome to get very detailed about what you'd like to see in the audio summarization features :)

**Comment by EricaVain** [comment]
Gotcha! Thanks anyway Thomas and I appreciate the response.
