### ISSUE TITLE
iOS App to record and upload files to cloud storage provider

### ISSUE THREAD

**Issue by vaughanhale** [TomFrankly/pipedream-notion-voice-notes#4]
Do you have any recommendations on iOS Apps that can easily / automaticly upload a voice recording to a cloud storage provider?

**Comment by TomFrankly** [comment]
Hey @vaughanhale,

We're building one! You can sign up for the waitlist here: https://flylighter.com/

The app will start out as a web clipper for Notion (the best one you've ever seen), and then we'll quickly be adding voice-recording and AI features.

In the mean time, there is only **one** app that auto-uploads files to Cloud Storage as far as I know, and that's RecUp. It's an iOS-only app, and it only works with Dropbox. (I've looked _everywhere_ for another option; I can't find one.)

Beyond that, Dropbox does have an Upload File action in the iOS Shortcuts app that you can pair with the Record Audio action. As far as I can tell, only Dropbox has bothered to create Shortcuts actions like this.

In Flylighter, we'll be adding auto-upload options for Google Drive, OneDrive, and Dropbox, provided there aren't any major roadblocks we run into for them.
