### ISSUE TITLE
Got as far as cleaning up then got this...

### ISSUE THREAD

**Issue by KellyHarvell** [TomFrankly/pipedream-notion-voice-notes#41]
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)
I have no clue what this means.
I tried a much shorter recording and still got the error.

**Comment by TomFrankly** [comment]
@KellyHarvell can you post your logs from the Logs tab? That'll help us figure out where the bug happened.

**Comment by beppojs** [comment]
I have a very similar issue trying to process a 78MB file via Dropbox. The trigger works, but the problem is with the `notion_voice_notes` step.

In the logs:
`This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: FSReqCallback, Learn more: https://pipedream.com/docs/code/nodejs/async/)`

The Error message:
Error: Failed to download file: Response code 410 (Gone)

` at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:316:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1885:5)
    at null.executeComponent (/var/task/launch_worker.js:242:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:748:28)`

I am using version `0.7.0` with the default settings (Enable Advanced Options = False).

**Comment by KellyHarvell** [comment]
Here's the first part of the log...
I even truncated the file in case it helps so this is the shorter file.

11/6/2023, 5:53:11 PM
Checking that file is under 300mb...

11/6/2023, 5:53:11 PM
File size is approximately 5.8mb.

11/6/2023, 5:53:11 PM
File is under the size limit. Continuing...

11/6/2023, 5:53:11 PM
Checking if the user set languages...

11/6/2023, 5:53:11 PM
No language set. Whisper will attempt to detect the language.

11/6/2023, 5:53:12 PM
Downloaded file to tmp storage:

11/6/2023, 5:53:12 PM
{ path: '/tmp/test_recording.mp3', mime: '.mp3' }

11/6/2023, 5:53:12 PM
Successfully got duration: 724 seconds

11/6/2023, 5:53:12 PM
Chunking file: /tmp/test_recording.mp3

11/6/2023, 5:53:12 PM
Chunks created successfully. Transcribing chunks: chunk-000.mp3

11/6/2023, 5:53:12 PM
Transcribing file: chunk-000.mp3

11/6/2023, 5:54:41 PM
Attempting to clean up the /tmp/ directory...

11/6/2023, 5:54:41 PM
Cleaning up /tmp/chunks-2Xp1PTyPA2GUDPGjIYHVNoduHGa...

11/6/2023, 5:54:41 PM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify ca...

**Comment by TomFrankly** [comment]
I think this might be the case. Apparently they had a major outage this morning as well.

**Comment by KellyHarvell** [comment]
ChatGPT is working currently but I'm still getting an error. Here's the most recent log...

11/9/2023, 11:42:04 AM
Checking that file is under 300mb...

11/9/2023, 11:42:04 AM
File size is approximately 5.8mb.

11/9/2023, 11:42:04 AM
File is under the size limit. Continuing...

11/9/2023, 11:42:04 AM
Checking if the user set languages...

11/9/2023, 11:42:04 AM
User set transcript language to en.

11/9/2023, 11:42:04 AM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: FSReqCallback, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by beppojs** [comment]
After it didn't work for the last two days, today I re-uploaded the specific audio file again and now it worked. So for my error message posted above, it looks like an OpenAI issue.

**Comment by TomFrankly** [comment]
@KellyHarvell just chatted with Pipedream about this, and we're thinking it's an OpenAI issue combined with a false positive triggering the warning on Pipedream's end: https://pipedream.com/docs/code/nodejs/async/#false-positives
