### ISSUE TITLE
Failed to download file: Response code 410 (Gone)

### ISSUE THREAD

**Issue by weseeclearly** [TomFrankly/pipedream-notion-voice-notes#44]
I updated to the newest version, and now getting this error:

Failed to download file: Response code 410 (Gone)

This is the log:

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/78986062/53414d10-763f-4c46-a477-90115d168e17)

**Comment by weseeclearly** [comment]
![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/78986062/d2a1457f-da26-4886-b09a-a96b0e5d6945)

**Comment by TomFrankly** [comment]
@weseeclearly are you using Dropbox? And if so, is this the result of re-running a workflow that failed earlier?

With Dropbox specifically, files only get a public link for a couple of hours – then it expires. So in case where the link has expired, you have to re-upload the audio file.
