### ISSUE TITLE
Notation to Notes issue on Create Transcript

### ISSUE THREAD

**Issue by Roadglide2020** [TomFrankly/pipedream-notion-voice-notes#5]
I am getting the error mp ecording.m4a does not exist on this step.
All previous steps complete and it appears that the file is downloaded according to the  download summary from the variables
This is the No Code version for Google Drive. I really want to get this working!!!

Thank you in advance.

Tony Ashby

**Comment by TomFrankly** [comment]
Hey @Roadglide2020! Can you try the latest version of the workflow? That should solve this: https://www.youtube.com/watch?v=A3pymMz0o-M
