### ISSUE TITLE
Voice Notes for Notion Not Working

### ISSUE THREAD

**Issue by alexramsbottom** [TomFrankly/pipedream-notion-voice-notes#53]
I've tried 10+ times to get voice recordings transcribed and summarized in my Ultimate Brain for Notion. This is the full error message:

 at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:267:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:764:28)

I've been using DropBox as the source for running the program.

I've tried updating my workflow, as well as plugging in new API keys from OpenAI, making sure my billing info is correct for OpenAI, and using different source folders and recordings in my dropbox to sense-check if one was materially different than the others.

I'm not sure what this question means, "**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**"

Contents of Logs tab from the notion_voice_notes action step are attached as a PDF file. Thanks and let me know if there's something I'm doing incorrectly on my end!
[voice notes action step error log.pdf](https://github.com/TomFrankly/pipedream-notion-voice-notes/files/13641956/voice.notes.action.step.error.log.pdf)

**Comment by TomFrankly** [comment]
@alexramsbottom looking at the logs, this seems like an OpenAI issue. You can see in the latter half of the logs that OpenAI is failling to transcribe the file.

I'm not sure what the actual error is on their side, as it's not returning a status code or any other helpful information 😕

I'll note that we're working on incorporating this workflow into our app, Flylighter: https://flylighter.com/

And one thing we'll be doing is trying out addtional transcription methods that don't rely on OpenAI. You can join our waitlist on that site! Hoping to launch our mobile beta in January 🙂
