### ISSUE TITLE
Error message on final test

### ISSUE THREAD

**Issue by Quiscodelcerro** [TomFrankly/pipedream-notion-voice-notes#6]
I get the following while using the suggested test file in google drive and having vpn turned off:
Error
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI: undefined Connection error.

DETAILS
    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:363:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/2877cde0cb601751826e758c481d9e35ace6f9c6c767176b83320fa7861e6f28/code/Notion-Voice-Notes.mjs:1859:22)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

![log tes](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/123990646/5cbbea5c-ba55-4d39-875d-44a41bf5f514)
![noption test 2](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/123990646/a330790f-da2d-46db-958b-a2de91f8a476)

**Comment by TomFrankly** [comment]
This seems like it might be a connection error with the OpenAI API. There's not much detail in the error message.

Can you try testing it again?

If you're using the Google Drive or OneDrive versions, you'll need to test your download step as well in order to get the file back into temp storage.

For Dropbox, you may need to upload a new file to Dropbox and test with that. Dropbox only allows auto-generated download links to be public for a couple of hours.

**Comment by joelcm13** [comment]
Came here to post. Running into this same issue as well. I've tried the full re-test process a couple times and kept hitting this same thing. Also tried deploying to test live and got the same issue. Let me know if there's anything else I should test!

**Comment by kvamis01** [comment]
I had this same error, then realized I hadn't set up a paid plan with OpenAI yet. Set that up, re-tested, it still failed. Waited, retested the entire workflow again, and it was successful. Maybe double-check your billing is set up and correct with OpenAI?

**Comment by TomFrankly** [comment]
I think that is indeed the option. Waiting for any reports of the same error from people who have verified that they've added billing info and generated a new API key; until then, I'll close this issue.
