### ISSUE TITLE
Timeout in notion_voice_notes

### ISSUE THREAD

**Issue by patrickcost** [TomFrankly/pipedream-notion-voice-notes#62]
**Describe the bug**
Timeout in notion_voice_notes

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
DropBox

**Have you tried updating your workflow?**
Yes. Tried recreating from scratch. Also tried with fresh Pipedream, OpenAI API key and OpenAI account.
Tried initially with GPT4-preview, then GPT4, then GPT3.5 turbo, multiple times on different hours and different days. Seems unlikely to be a congestion issue on OpenAI's end.

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Both

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**
TIMEOUT
TIMEOUT

DETAILS
TIMEOUT: TIMEOUT
    at Timeout._onTimeout (file:///var/task/lambda_handler.mjs:934:23)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

... ... ...
024-01-15, 09:50:01
Full file size: 0.8435888290405273mb. Chunk size: 24mb. Expected number of chunks: 1. Commencing chunking...

2024-01-15, 09:50:01
Created 1 chunk: /tmp/chunks-2az5VdBFzHmgMaK8DYPNViCmXZv/chunk-000.m4a

2024-01-15, 09:50:01
Chunks created successfully. Transcribing chunks: chunk-000.m4a

2024-01-15, 09:50:01
Transcribing file: chunk-000.m4a

2024-01-15, 09:51:29
Encounted error from OpenAI: Connection error.

2024-01-15, 09:51:29
Status code: undefined

2024-01-15, 09:51:29
Error name: Error

2024-01-15, 09:51:29
Error headers: undefined

2024-01-15, 09:51:29
Encountered a recoverable error. Retrying...

2024-01-15, 09:51:29
Retrying transcription for chunk-000.m4a due to error: Error: Connection error.

2024-01-15, 09:51:31
Transcribing file: chunk-000.m4a

2024-01-15, 09:52:59
Encounted error from OpenAI: Connection error.

2024-01-15, 09:52:59
Status code: undefined

2024-01-15, 09:52:59
Error name: Error

2024-01-15, 09:52:59
Error headers: undefined

2024-01-15, 09:52:59
Encountered a recoverable error. Retrying...

2024-01-15, 09:52:59
Retrying transcription for chunk-000.m4a due to error: Error: Connection error.

2024-01-15, 09:53:01
Transcribing file: chunk-000.m4a

2024-01-15, 09:54:29
Encounted error from OpenAI: Connection error.

2024-01-15, 09:54:29
Status code: undefined

2024-01-15, 09:54:29
Error name: Error

2024-01-15, 09:54:29
Error headers: undefined

2024-01-15, 09:54:29
Encountered a recoverable error. Retrying...

2024-01-15, 09:54:29
Retrying transcription for chunk-000.m4a due to error: Error: Connection error.

2024-01-15, 09:54:37
Transcribing file: chunk-000.m4a

**Comment by TomFrankly** [comment]
Hi @patrickcost,

This seems like an error on OpenAI's end; it's possible their servers are overloaded.

The other possibility is that your API key is expired: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#openai-error

But if that's not the case, unfortunately the only thing we can do when this happens is wait and try again later. In this case, OpenAI is returning a generic "Connection Error" that indicates no possible fixes.
