### ISSUE TITLE
Set up process snag

### ISSUE THREAD

**Issue by seeinghuman** [TomFrankly/pipedream-notion-voice-notes#68]
**Describe the bug**
Not a bug, but a lack of knowledge on my part I guess.
In step 7, what is my notes database referring to exactly?

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Dropbox

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

**Comment by TomFrankly** [comment]
@seeinghuman any Notion database will work! I just labeled that field "Notes Database" since most people use this workflow to take voice notes.

Here's my guide to Notion databases: https://thomasjfrank.com/notion-databases-the-ultimate-beginners-guide/

Hope that helps!

**Comment by seeinghuman** [comment]
Thanks for the quick reply!
My first test failed and I'm not sure how to proceed.

It came back with "Failed to create Notion page."

**Comment by TomFrankly** [comment]
Not sure why that'd be happening, but if you can provide the info the bug post template asks for, it'll help me debug the issue!

**Comment by seeinghuman** [comment]
I added the field and got another error

@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'Duration (seconds) is expected to be rich_text. AI Cost is expected to be rich_text.'
  
  I went back to Notion and don't see an option for rich text

**Comment by TomFrankly** [comment]
@seeinghuman ah, that's a bit odd! Did you select values for those fields in the Pipedream action?

You can leave them blank, but I think they're supposed to only allow you to select properties of the right type. Both of those should be number-type properties.

If you change their type to Number in Notion, things should work.

I'd also recommend using this process to check if your workflow is updated, and updating if not: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

As for "rich_text", that's the API's name for the "Text" property type that you can see in Notion. It's the default type for new properties.

**Comment by seeinghuman** [comment]
Yes, I added the field names you used in your example, because they looked useful.

I had "text" (was the default) selected and there was no "rich-text" option, but changing it to #numbers worked! So thank you for you quick and efficient help!

Oh, I tried to look into the update status / process and am not finding a screen that looks the same. I didn't see "workflows" on the sidebar menu, so I'm not exactly sure what you have selected there.

**Comment by seeinghuman** [comment]
Maybe there's no edit option because it says "deploy pending"

**Comment by TomFrankly** [comment]
@seeinghuman if you're in the editor and refresh the page, you should be able to see if there are any updates available by looking here:

![CleanShot 2024-02-05 at 15 48 45@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/d2fc6271-408f-495d-914c-81172c8c896e)

Glad the property change worked for you!

**Comment by seeinghuman** [comment]
I "updated" to most recent version and tried to run it by placing new files in the Dropbox folder. It came back with an error on the "notion-voice-notes" pane.

Error
Failed to create Notion page.

DETAILS
    at Object.createNotionPage (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1677:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:2163:30)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

**Comment by TomFrankly** [comment]
Can you post a screenshot of your Logs tab? Or copy and paste the last few lines?

The actual error from Notion should be there.

**Comment by seeinghuman** [comment]
Here's a PDF from a link that was emailed to me
[Uploading screencapture-pipedream-seeinghuman-event-history-2by54kqSRlTnmkVU1CguIcNUaqd-2024-02-05-15_12_15.pdf…]()

**Comment by TomFrankly** [comment]
You may have submitted that last message too quickly, as that link just links to this Github issue!

**Comment by seeinghuman** [comment]
[Uploading screencapture-pipedream-seeinghuman-event-history-2by54kqSRlTnmkVU1CguIcNUaqd-2024-02-05-15_12_15.pdf…]()

**Comment by TomFrankly** [comment]
Same issue, unfortunately!

![CleanShot 2024-02-05 at 16 52 21@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/07aeb2ba-4f38-4b1c-8207-f92a792831e2)

You can simply copy the last few rows of the Logs tab to your clipboard and paste them if that's easier.

**Comment by seeinghuman** [comment]
Sorry about all that. Here's the end of the log:


@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one:\n' +
    'body.icon.emoji should be defined, instead was `undefined`.\n' +
    'body.icon.external should be defined, instead was `undefined`.'
}

2/5/2024, 3:05:46 PM
Error creating Notion task:     at null.buildRequestError (/pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1660:19)
    at Object.createNotionPage (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1656:5)
    at Object.run (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:2163:30)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)
 {
  name: 'APIResponseError',
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one:\\nbody.icon.emoji should be defined, instead was `undefined`.\\nbody.icon.external should be defined, instead was `undefined`.","request_id":"2d755172-73f1-45c2-8418-bd62e028aa94"}'
}

**Comment by TomFrankly** [comment]
For that, you should just need to set the page icon setting! It should have been set to an emoji of a robot by default.

**Comment by seeinghuman** [comment]
I changed it and tried again, There's a different error in Pipedream.
After the first occurrence of the error, I deleted the file from Dropbox and then replaced it with another copy. Same error:

Error
Failed to download file: Response code 410 (Gone) 
    at Object.downloadToTmp (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:331:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1973:5)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

**Comment by seeinghuman** [comment]
From the log
db["dropbox_state"] ⭅ {"path":"/Public/NotionVoiceTranscribe","recursive":false,"cursor":"AAHm8QwO2jhsAifn6ffSqeJHVCpOj7T9NfgyTSVVy07MNkM6b_BFy0k_6q1yAlULLNieIjr4IzQ3yq2Njq1RrE86rDg8iZfHPH971Y_msM-KHLCw5drgL5sn8kXi-TGFV2o9TLk5fjodF5tvGIuC0w7TNsSwGHBHbhWzS8zaVSpX2QDxA9WJd9I8ll9El0iA59g7LAWxjh9LdGNszT5e7loPTyI2OP285ch3a11ThSy9vcV6vmYdmfyfBEBTvydNmtT48ihQUsO4LILTCA6MhOXE"}

**Comment by TomFrankly** [comment]
Dropbox expires their links after a couple hours. If you upload the file again (rename it), it should work.

**Comment by seeinghuman** [comment]
I tried with a different file and it's still "failing to crate notion page" (whatever that means)

Error
Failed to create Notion page. 
    at Object.createNotionPage (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1677:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:2163:30)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)
(notion_voice_notes)
details
Message:
Failed to create Notion page.
Total Duration:
48,664 ms
Compute Time:
48,336 ms
Execution Start:
2024-02-06T04:27:56.854Z
Execution End:
2024-02-06T04:28:45.518Z
Steps Executed:
1 / 1
Credits:
2
Version:
20 (d_Zds6xRjy)

**Comment by seeinghuman** [comment]
2/5/2024, 8:28:45 PM
@notionhq/client warn: request fail {
  code: 'validation_error',
  message: 'body failed validation. Fix one:\n' +
    'body.icon.emoji should be defined, instead was `undefined`.\n' +
    'body.icon.external should be defined, instead was `undefined`.'
}

2/5/2024, 8:28:45 PM
Error creating Notion task:     at null.buildRequestError (/pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/errors.js:162:16)
    at Client.request (/pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/node_modules/.pnpm/@notionhq+client@2.2.14/node_modules/@notionhq/client/build/src/Client.js:378:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.retry.retries (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1660:19)
    at Object.createNotionPage (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1656:5)
    at Object.run (file:///pipedream/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:2163:30)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)
 {
  name: 'APIResponseError',
  code: 'validation_error',
  status: 400,
  headers: Headers {
    [Symbol(map)]: [Object: null prototype] {
      date: [Array],
      'content-type': [Array],
      'content-length': [Array],
      connection: [Array],
      'x-powered-by': [Array],
      'x-notion-request-id': [Array],
      etag: [Array],
      vary: [Array],
      'cf-cache-status': [Array],
      'set-cookie': [Array],
      server: [Array],
      'cf-ray': [Array]
    }
  },
  body: '{"object":"error","status":400,"code":"validation_error","message":"body failed validation. Fix one:\\nbody.icon.emoji should be defined, instead was `undefined`.\\nbody.icon.external should be defined, instead was `undefined`.","request_id":"c3bf7477-5886-436a-b77f-4092d101eddf"}'
}

**Comment by seeinghuman** [comment]
Is this what you meant by icon?
<img width="644" alt="Screenshot 2024-02-05 at 8 34 59 PM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/113387531/2a050df4-0ace-43df-8dfb-14613da0cd21">

**Comment by seeinghuman** [comment]
You're being so helpful I hate to keep coming with more issues. There were no options there, and the instructions said I could type it in, I typed "robot" and now I have this error and no idea to get out of it.

<img width="982" alt="Screenshot 2024-02-05 at 9 35 56 PM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/113387531/29766f44-b82f-4802-bdef-957bc8d14367">

**Comment by TomFrankly** [comment]
Hmm, honestly at this point I think you should click the link again and set the workflow up from scratch: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#copy-my-workflow

I just haven't seen this number of issues come up before, so perhaps something went wrong during the workflow duplication process.

I've created a video for you showing every step of this setup process in detail, ending with a successful test: https://www.loom.com/share/c6db525dcb114145a1674d4c05855a75?sid=7fe3d80f-eafa-4dc0-b7fc-fa847008dcd3

**Comment by seeinghuman** [comment]
Hi Frank,

I agree it mades sense to start over. I’ve just around to this now and it went ok - except at the test stage I got a “failed to download" error. Here’s the error contents, and I’m hoping you can see what I need to do to make it work.

Thanks!
Darryl

￼

Error
Failed to download file: getaddrinfo ENOTFOUND ud78r9s3t6c6s7afa545778b4100.dl.cloudstorageusercontent.com
DETAILS
    at Object.downloadToTmp (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:331:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/1f555395881e5b79fbe9431588e45c7f9763b0394fdc7e0eaabc4ff53300ac5d/code/Notion-Voice-Notes.mjs:1973:5)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

Exports

Inputs

Logs

Details

Detailed/code mode
OpenAI (ChatGPT) Account
DropboxNotionVoice Transcribe
Notion Account
***@***.***
Previous Step Data (Set by Default)
{ "trigger": { "event": { ".tag": "data", "client_modified": "2030-01-22T20:39:35Z", "content_hash": "99018994bda76c25de2613871a6c354f1059f879b03786284924ee5568145674", "id": "id:BCd78_dtB7AAAAAAAAAAm2", "is_downloadable": true, "link": "https://ud78r9s3t6c6s7afa545778b4100.dl.cloudstorageusercontent.com/cd/0/get/C-64shEc-r56kB0jBeGPoKnGTbQtlliGe8kZds_3ZXZOcCaXYfMxyd9zLaZ1eaQWDTu1BgQriOM_hxup6T39aCzc8juqf7ftEr4Y0SCwTGdEZcXbnOyPp4aQ9EfryE3p8_N3W2eNUc_WdZQhUfVOpdfZGsQ8fce7p_ynCV71KwB9Dx2cBQkKb4EJ7FZRVmtYUl/file", "name": "sound-sample-10mins.mp3", "path_display": "/Users/sample-sound-10mins.mp3", "path_lower": "/users/sample-sound-10mins.mp3", "rev": "025de20479j6e65000000150r508q9r", "server_modified": "2030-01-22T20:39:35Z", "size": 5200935 }, "context": { "id": "2cbk8IOd7P3uz57Mb3nGFZvDFdv", "ts": "2024-02-20T00:05:04.829Z", "pipeline_id": null, "workflow_id": "p_YyCNrAL", "deployment_id": "d_ybsMK3p1", "source_type": "TRACE", "verified": false, "hops": null, "test": true, "replay": false, "owner_id": "o_MMIoWlW", "platform_version": "3.47.4", "workflow_name": "Notion Voice Notes 2 Workflow(Dropbox)", "resume": null, "emitter_id": "dc_jkuE1Eb", "trace_id": "2cbk8IOd7P3uz57Mb3nGFZvDFdv", "JIT": true, "attachments": {} } } }
Summary Options
[ "Summary", "Main Points", "Action Items", "References" ]
Notes Database
Voice Transcriptions
50b25427-911b-4cb2-9496-bcfc938e3491
Note Title (Required)
Name
Note Duration
Duration
Note Cost
AI Cost
Note Tag
Tags
Note Page Icon
🤖
Note Tag Value
voice note
ChatGPT Model
gpt-3.5-turbo
Enable Advanced Options
false

Test

Test to deploy

**Comment by seeinghuman** [comment]
I ran it again, using the “generate test file” option. The error from logs is here:

This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: FSReqCallback, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by TomFrankly** [comment]
Generate Test File won't work, and the program should throw an error letting you know – you'll need to upload a real audio file! And it needs to be a newly uploaded file. Dropbox only exposes download links for a couple hours.

**Comment by seeinghuman** [comment]
I got it working but have a question about an issue. Instead of retaining the audio file name for the Name field in Notion, it appears to be creating its own title / Name based on the general essence of the recording. This is going to make it terribly difficult to keep track of which audio files have been transcribed… 

Do you know I can alter the way this is working?

Thanks!

**Comment by TomFrankly** [comment]
Yes, you should be able to add an Update Page step after the final step: https://pipedream.com/apps/notion/actions/update-page

Then you can find the filename from the first step, hit Copy Path, and set that as the title:

![CleanShot 2024-02-20 at 13 01 57@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/a09af717-a030-46fd-8f6c-8ff1e3623720)

I won't be able to provide additional support for this though, as it's an extension of functionality. I can only support the app as it's currently built – we'll be adding future improvements to this workflow to our upcoming [Flylighter mobile app](https://flylighter.com/).

**Comment by seeinghuman** [comment]
Thanks for the reply. First, I’m no coder so I’m not following this very well. It looks like you’re suggesting a change in the Trigger Component?

Before I attempt something that I don’t understand at all, I wonder if you can provide some quick replies:

Isn’t this file name creation something that has been built as part of your workflow?

Or does it come from something that already existed that you incorporated?

If I do manage to figure out how to make the change, will updates from you in the future overwrite that change?

If making adjustments is the way forward, would it be easier to add a field that uses the original name and still allow this name process to occur as it is now? (I could add an “Original File Name” field in Notion  - and might accept that doing this manually is the safest, though not most efficient solution.)

**Comment by TomFrankly** [comment]
Name creation happens in the workflow, but you can add an other custom step at the end to change it as I've suggested.

My updates only affect the notion_voice_notes Action, and only if you manually update the action. No overwrites to additional actions you add to the workflow – the workflow itself is yours. It just has actions I built in it.

I'll leave the rest up to you to explore and test yourself! I have Pipedream tutorials planned, but their docs are also helpful: https://pipedream.com/docs
