### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by malikayesha88** [TomFrankly/pipedream-notion-voice-notes#69]
Hi Thomas. I keep getting the same error message, but I know I have a paid AI account. Any advice? Thank you so much by the way.

An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.
DETAILS
    at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

I am using DropBox

**Comment by TomFrankly** [comment]
@malikayesha88 can you try running the automation again?

This is an API Connection Error, which likely means that OpenAI was overwhelmed at the time and couldn't handle the request.

**Comment by malikayesha88** [comment]
Thanks Thomas! I fixed it. My next question is - is there some way to change the automation so that it can generate the audio file into a "book chapter" or creative writing?

**Comment by TomFrankly** [comment]
@malikayesha88 not within the notion_voice_notes action itself, but if you check the Exports tab on that action when it successfully runs, you'll notice that I return nearly every piece of information you could want.

That includes the full transcript, so you could easily add additional steps to the workflow. For example, you could add another OpenAI -> Chat step and pass it the transcript with a prompt like "Rewrite this transcript so it would read well as a chapter in a book".

Hope that helps!
