### ISSUE TITLE
Invalid duration number 

### ISSUE THREAD

**Issue by planginc** [TomFrankly/pipedream-notion-voice-notes#7]
apologies in advance if I'm not doing this correctly, it's my first time posting to github. 
![Duration1](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/5d4fc7f1-3f50-4a5f-ba41-6327e33db195)
![Duration2](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/bb460024-e8be-41ba-879b-c0a137039bec)

**Comment by TomFrankly** [comment]
Oh this one is interesting. The log is saying that the duration is "NaN Seconds" (non a number)

Do you know how long the file is? And what app you used to create it?

I've uploaded a lot of mp3 files in testing, but haven't run into an error like this.

**Comment by planginc** [comment]
This file is 1:52 and here's the app (so glad this one wasn't a "Pam" thing...lol)  

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/2c880bfd-9723-4b1a-872b-2b57f11323f6)

**Comment by planginc** [comment]
You might be onto something, it might be the app,  The duration and cost have never worked for me, but you can see it DID pick up it for your 1% rule.

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/b015c8e2-0655-4e28-a3db-f9bed3d277b9)

**Comment by TomFrankly** [comment]
Ah, I'm betting the app encodes the mp3 file in a weird way that doesn't let my script get the duration. Is there another app you can try?

**Comment by planginc** [comment]
sure, I'll try it again tomorrow. tysm, I appreciate your help w/this! :)

**Comment by planginc** [comment]
I changed apps.....good call lol
![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/6b5e82b6-905c-41bc-8c8b-9cce565f9aa5)

**Comment by planginc** [comment]
![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/143378555/2c8e70d2-816b-41e2-a219-e39f3b5d54a0)

**Comment by TomFrankly** [comment]
Oh good! I think I'll try writing a fallback that converts the file to mp3 if m4a fails, but this is still great to see.
