### ISSUE TITLE
Connecting to Ultimate Brain

### ISSUE THREAD

**Issue by planginc** [TomFrankly/pipedream-notion-voice-notes#8]
I purchased Ultimate Brain/Creators Companion today but it's not showing up as an option to connect to it. I was NOT required to connect notion today because I already connected it when I set this up using the coded version a couple months ago. 

I'm not sure how to get it to pick up a new data base?  It's been several hours now since I've added it to my notion. I quit notion and launched it again. Same with Pipedream. I deleted every project I had in pipedream and then logged out, logged back in and started over. I'm not sure how to connect it to my shiny new database - any ideas?!  Should I be asking pipedream?

**Comment by TomFrankly** [comment]
Hi @planginc!

If you're not seeing your database, you can add it manually by navigating to the database, then hitting the 3-dot menu and adding Pipedream from the Connections sub-menu.

![image](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/30671e74-72c7-4f2a-9a6e-6780c487af60)

Once you've done that, you should see it pop up! It all comes down to the integration having access to the specific page. And if permission has been revoked from that page before, then granting permission to a parent page won't automatically re-grant it, I believe.

Hope that helps!

**Comment by planginc** [comment]
omggg - I knew this from doing the previous one...I forgot - so sorry! lol  I was stuck on trying to get the code from the link.  I think I need to shut my computer down for the night lol  tysm!!
