### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'raw_transcript')

### ISSUE THREAD

**Issue by ippo5982** [TomFrankly/pipedream-notion-voice-notes#80]
Hello

yesterday after a succesfull process, it started to give me this error, 

TypeError: Cannot read properties of undefined (reading 'raw_transcript')

from the details I was not able to understand the problem. Here I tried to put an screenshot of the details, if someone can help me with this.

![Immagine 2024-03-27 090411](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/165139011/bc364034-33f9-455e-9ace-dcc3955245c3)

Thank you very much in advaced.

Kind regards

**Comment by TomFrankly** [comment]
@ippo5982 do you know if you changed your transcription service in the settings at all?

**Comment by TomFrankly** [comment]
@ippo5982 I just tried recreating the workflow from scratching using my template link, and it's working as expected using both OpenAI and Deepgram as transcription options. However, I'll note the Deepgram option is in beta and might not work as expected, and that error seems to indicate Deepgram is selected.

![CleanShot 2024-03-28 at 15 52 49@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/f4cca2f5-c56d-4895-b842-44619e3d2c65)

The only part of the current action's code that tries to read `raw_transcript` is here:

![CleanShot 2024-03-28 at 15 54 06@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/71de4eff-d126-48d9-ac06-4f03865a1578)

The only thing I can think of here is that your Transcription Service property is somehow blank. I think that could only happen if you manually cleared it; can you check and make sure one of the two options is selected?

**Comment by ippo5982** [comment]
Hello @TomFrankly 

Actually I didn't change anything, but based on your last hint I simply opened the drop down menu for choosing the servive and click on OpenAi even if this was already choosen. After this, everything start to work flawlesslly again.😊
It's like when you have to shutdown something to make it working again. 😂

Thank you very very much for everything.

Best regards

**Comment by TomFrankly** [comment]
@ippo5982 glad that worked! The value must have gotten cleared out on the backend somehow, even if it was still showing. I'll add a fix for this when I can.
