### ISSUE TITLE
Cannot select Notes database on setup

### ISSUE THREAD

**Issue by thomasoteixeira** [TomFrankly/pipedream-notion-voice-notes#82]
**Describe the bug**
It's impossible to complete the setup of the workflow, specifically on the Notion setup step as whenever I try so select the Notes database, the dropdown is way too low and the options are hidden on the end of the page. Cannot scroll further to select the notion page. Tried on different browsers. Same result.

<img width="615" alt="image" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/116651793/7fb459ff-d215-488e-8902-402ab22b75e1">

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Google Drive

**Have you tried updating your workflow?**
Please follow the steps here, and ensure you've tested the latest version of the workflow: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#update

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Couln't finish setup.
**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

**Comment by thomasoteixeira** [comment]
It's a big one, actually. 28 inches 4k.
The screenshot is from the bottom left side of the screen. Tried to resize the zoom with no success. I imagined it would be something related to the pipedream page bug. How should I report it to them?
Thanks!

**Comment by thomasoteixeira** [comment]
See the screenshot below. I think it will be easier to understand now. The selection list for the notes database opens up on the very bottom of the right side of the screen and there's no way to scroll down to select it.
I'll open an issue with Pipedream as well.

<img width="2304" alt="Screenshot 2024-04-04 at 11 45 45 AM" src="https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/116651793/1d8cc934-a19a-4f46-954e-f7990ded9964">

**Comment by TomFrankly** [comment]
@thomasoteixeira ah, you somehow have their brand new alpha-stage editor turned on. Even I haven't tried that yet, although I've seen a demo of it.

If you back out of the workflow builder, you should be able to go to Settings -> Alpha and turn off the alpha builder.

![CleanShot 2024-04-04 at 12 41 32@2x](https://github.com/TomFrankly/pipedream-notion-voice-notes/assets/684961/9bda55c1-8f4f-45c3-9fb0-1e79d0d6f02c)

**Comment by TomFrankly** [comment]
Just chatted with their team; you can also try adding `?v2=1` to the end of the builder URL to turn off the new builder in case this first option doesn't work.
