### ISSUE TITLE
Error occured while attempting to split the file into chunks

### ISSUE THREAD

**Issue by BryanKofsky** [TomFrankly/pipedream-notion-voice-notes#84]
**Describe the bug**
Error
An error occured while attempting to split the file into chunks, or while sending the chunks to OpenAI. If the full error below says "Unidentified connection error", please double-check that you have entered valid billing info in your OpenAI account. Afterward, generate a new API key and enter it in the OpenAI app here in Pipedream. Then, try running the workflow again. If that does not work, please open an issue at this workflow's Github repo: https://github.com/TomFrankly/pipedream-notion-voice-notes/issues Full error from OpenAI: Connection error.

Details:
 at Object.chunkFileAndTranscribe (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:391:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/4cf355a52ab0f9c275ba953eea42492276c4b796f961fdffefa87942b1ced4df/code/Notion-Voice-Notes.mjs:1901:22)
    at null.executeComponent (/var/task/launch_worker.js:287:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:786:28)

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**

Google Drive

**Have you tried updating your workflow?**

Yes, including setting up a completely new instance. 

**Does the issue only happen while testing the workflow, or does it happen during normal, automated runs?**
Both

**Please paste the contents of your Logs tab from the notion_voice_notes action step.**

 PM
Checking that file is under 300mb...

4/8/2024, 2:38:51 PM
File size is approximately 6.1mb.

4/8/2024, 2:38:51 PM
File is under the size limit. Continuing...

4/8/2024, 2:38:51 PM
Checking if the user set languages...

4/8/2024, 2:38:51 PM
No language set. Whisper will attempt to detect the language.

4/8/2024, 2:38:51 PM
Successfully got duration: 256 seconds

4/8/2024, 2:38:51 PM
Chunking file: /tmp/Sample Audio File (1).mp3

4/8/2024, 2:38:51 PM
Chunks created successfully. Transcribing chunks: chunk-000.mp3

4/8/2024, 2:38:51 PM
Transcribing file: chunk-000.mp3

4/8/2024, 2:40:21 PM
Attempting to clean up the /tmp/ directory...

4/8/2024, 2:40:21 PM
Cleaning up /tmp/chunks-2epVUoZNcUwgowtHo50YpqBVYPe...

4/8/2024, 2:40:21 PM
ACTIVE_HANDLE
This step was still trying to run code when the step ended. Make sure you promisify callback functions and await all Promises. (Reason: ChildProcess, Learn more: https://pipedream.com/docs/code/nodejs/async/)

**Comment by TomFrankly** [comment]
@BryanKofsky if your account has real-money credits (non-promo credits), and you're using an API key you generated after adding those credits, then this is just due to OpenAI's service being overloaded with requests.

"Connection Error" means OpenAI rejected the connection request. I don't think there's anything we can do other than try again later when it happens, and within the limitations of Pipedream's free account, that means you'll need to go into the Pipedream dashboard and Replay the failed run.

**Comment by BryanKofsky** [comment]
Interesting. I'm paid on open AI, but not pipe dream... Yet.

It's been like that for a while now. Thanks, for the quick response!

Bryan Kofsky
Sales Engineer | Growth Marketer | Tech Enthusiast

🌐 www.bkofsky.com
📞 419-825-6723
💼 https://www.linkedin.com/in/bkofsky/

**Comment by TomFrankly** [comment]
@BryanKofsky yeah it's a tough one. I don't believe upgrading to a paid Pipedream account will fix it.

I've just messaged the Pipedream team to double-check if there's anything in the underlying infrastructure that would be causing the issue, but I still think it's due to OpenAI being overloaded.

Nearly everyone who reports this issue solves it either by adding credit at OpenAI (not ChatGPT Plus) and making a new API key, or just by waiting and trying again if they already did that first step.

My guess is that the Whisper endpoint in particular gets overloaded at times.

**Comment by BryanKofsky** [comment]
You rock, thank you! I will keep an eye on that.... Instead of resetting it
up from scratch to see if there's any issue from a lack of update or
something on my end.

I met with a friend (younger brother of a good friend) who was showing me
his process for YouTube ideation and scripting, and he mentioned to his
teammate, this is why we need a record this stuff. Ding ding ding! 😆 He
was mind-blown at the possibilities for this.

Bryan Kofsky
Sales Engineer | Growth Marketer | Tech Enthusiast

🌐 www.bkofsky.com
📞 419-825-6723
💼 https://www.linkedin.com/in/bkofsky/

**Comment by TomFrankly** [comment]
Yeah it's super helpful! I record the ideas for most of my videos using this now.

Definitely no need to set up the entire workflow from scratch here; hopefully if you try again later, the issue will be resolved.

Btw, my team and I are also working on a new tool: https://flylighter.com/

We're very near releasing our web clipper. Once we have our mobile app out, we'll be adding this voice notes workflow to it and making it much, much better – for example, in this version, it's not at all easy to have different voice-recording destinations for different purposes. In Flylighter, it'll be trivial.

**Comment by BryanKofsky** [comment]
Dude, I'm using UBCC and Flylighter beta 😎 The feature coming to the
mobile app is awesome to know though.

Side note: interesting in my journey how I just started using the b-roll
database. And now it looks like the sponsorship side of the template is
going to become extremely helpful. Your stuff has helped my a lot, and
continues as I grow (baby steps).

Bryan Kofsky
Sales Engineer | Growth Marketer | Tech Enthusiast

🌐 www.bkofsky.com
📞 419-825-6723
💼 https://www.linkedin.com/in/bkofsky/
