### ISSUE TITLE
You've reached your daily credits quota - Look like Pipedream change their daily credit quota for the Free Tier

### ISSUE THREAD

**Issue by sean3318** [TomFrankly/pipedream-notion-voice-notes#93]
**Describe the bug**
Not a bug, but it's heads up about the free tier on Pipedream.

**Which cloud storage app are you using? (Google Drive, Dropbox, or OneDrive)**
Dropbox

After getting transcripts for three videos, I got this message from Pipedream. You've reached your daily credits quota. Now, it's 25 credits for the free tier. If this is the wrong place for this, let me know.

**Comment by TomFrankly** [comment]
Hey @sean3318 - Pipedream did indeed update their Free tier, but it should be 10 credits/day with a max of 300/mo: https://pipedream.com/pricing

Not as good as before, but still quite good for a free tier.

The only most cost-effective option I know of right now is n8n, and only if you host an instance yourself: https://docs.n8n.io/hosting/ - I haven't done this myself, and I believe it requires understanding Docker and getting your own VPS (or self-hosting, but that may introduce security issues on your local network).

Our plan is to add this voice-notes functionality to Flylighter once we can launch a mobile app: https://flylighter.com/

We won't be able to offer it for free, but it'll be far cheaper than the $29/mo that Pipedream charges for their first paid tier. It'll also have a lot more flexibility than the current workflow - e.g. ability to capture to other destinations like Obsidian.

Hope this helps!
