### ISSUE TITLE
stuck in a loop

### ISSUE THREAD

**Issue by mitcheip** [TomFrankly/pipedream-notion-voice-notes#95]
Hi,

I'm quite new to PipeDream and followed the steps in the tutorial, but it hangs on the final step. I've tried using both Google Drive and Dropbox.

While testing, according to the log, it keeps trying to fix what it believes is a recoverable error.

This ends up using all of my PipeDream free time.

I'm not sure why it can't connect to OpenAI, which I think is why it gets stuck in a loop.

here is the log

TIMEOUT
TIMEOUT
Stack trace

Exports

Inputs

Logs

Details
23/09/2024, 21:26:29
Checking that file is under 300mb...

23/09/2024, 21:26:29
File size is approximately 6.1mb.

23/09/2024, 21:26:29
File is under the size limit. Continuing...

23/09/2024, 21:26:29
Checking if the user set languages...

23/09/2024, 21:26:29
No language set. Whisper will attempt to detect the language.

23/09/2024, 21:26:29
Setting the transcription service...

23/09/2024, 21:26:29
Logging settings...

23/09/2024, 21:26:29
Action Version::
No version detected
Audio File Chunk Size:
24 (default)
Chat Model:
gpt-3.5-turbo
Fail on no Duration:
Disabled (default)
Moderation Check:
Disabled (default)
Note Cost Property:
AI Cost
Note Duration Property:
Duration (Seconds)
Note Title Property:
Title
Summary Density:
2750 (default)
Summary Language:
No language set.
-more-
23/09/2024, 21:26:29
Setup stage duration: 0.276792ms

23/09/2024, 21:26:29
Total duration so far: 0.276792ms (0.000276792 seconds)

23/09/2024, 21:26:29
File path of Google Drive file: /tmp/Sample Audio File v3.mp3

23/09/2024, 21:26:29
Successfully got duration: 256 seconds

23/09/2024, 21:26:29
Download stage duration: 39.361705ms (0.039361705000000004 seconds)

23/09/2024, 21:26:29
Total duration so far: 39.638497ms (0.039638497 seconds)

23/09/2024, 21:26:29
Using OpenAI's Whisper service for transcription.

23/09/2024, 21:26:29
Chunking file: /tmp/Sample Audio File v3.mp3

23/09/2024, 21:26:29
Full file size: 5.86456298828125mb. Chunk size: 24mb. Expected number of chunks: 1. Commencing chunking...

23/09/2024, 21:26:29
Created 1 chunk: /tmp/chunks-2mTBejS1HnNNcLL99YNUdx5xWet/chunk-000.mp3

23/09/2024, 21:26:29
Chunks created successfully. Transcribing chunks: chunk-000.mp3

23/09/2024, 21:26:29
Transcribing file: chunk-000.mp3

23/09/2024, 21:27:58
Encountered error from OpenAI: Connection error.

23/09/2024, 21:27:58
Status code: undefined

23/09/2024, 21:27:58
Error name: Error

23/09/2024, 21:27:58
Error headers: undefined

23/09/2024, 21:27:58
Encountered a recoverable error. Retrying...

23/09/2024, 21:27:58
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

23/09/2024, 21:27:59
Transcribing file: chunk-000.mp3

23/09/2024, 21:29:28
Encountered error from OpenAI: Connection error.

23/09/2024, 21:29:28
Status code: undefined

Copy
23/09/2024, 21:29:28
Error name: Error

23/09/2024, 21:29:28
Error headers: undefined

23/09/2024, 21:29:28
Encountered a recoverable error. Retrying...

23/09/2024, 21:29:28
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

23/09/2024, 21:29:32
Transcribing file: chunk-000.mp3

23/09/2024, 21:31:02
Encountered error from OpenAI: Connection error.

23/09/2024, 21:31:02
Status code: undefined

23/09/2024, 21:31:02
Error name: Error

23/09/2024, 21:31:02
Error headers: undefined

23/09/2024, 21:31:02
Encountered a recoverable error. Retrying...

23/09/2024, 21:31:02
Retrying transcription for chunk-000.mp3 due to error: Error: Connection error.

23/09/2024, 21:31:09
Transcribing file: chunk-000.mp3

**Comment by TomFrankly** [comment]
HI @mitcheip,

It looks like you're getting a connection error from OpenAI.

Sometimes this happens to people who are using OpenAI's free promotional credit, and sometimes the fix is the following: https://thomasjfrank.com/how-to-transcribe-audio-to-text-with-chatgpt-and-notion/#openai-error

However, on other occassions this is just caused by OpenAI's API being overloaded and rejecting the request. I'd recommend trying the run again (you may need to re-upload the audio file with a changed name) and seeing if that works. If it doesn't, try the linked fix.

**Comment by mitcheip** [comment]
Thanks Thomas, it worked once I moved to paid openai.
