### ISSUE TITLE
[feature request] Support for Diarization

### ISSUE THREAD

**Issue by heyjustinai** [TomFrankly/pipedream-notion-voice-notes#97]
Hi, just stumbled upon this and this is amazing. Wondering if there is support for diarization as well? AFAIK whisper doesnt have diarization but deepgram have native diarization support.

Was going through the codebase and saw an implementation [here](https://github.com/TomFrankly/pipedream-notion-voice-notes/blob/cf10b60bd3f46fc863bc4dc6c5ffa399d486e0af/Notion-Voice-Notes-Beta.mjs#L757) on a commit 3 months ago, is that still beta?

**Comment by TomFrankly** [comment]
Hey @heyjustinai – yep, that feature is still in beta!

The version you've linked has some other issues that prevent me from shipping it as the public version – I believe they have to do with translations.

I've been working on a ground-up rewrite, which I'll hopefully get shipped in December. I'd love to work on it sooner, but for the moment I've got new Notion templates and a ton of YouTube content on my plate that I need to finish up first.

**Comment by heyjustinai** [comment]
awesome, looking forward to the release!
