### ISSUE TITLE
Issue with Summary Language Advanced in Workflow

### ISSUE THREAD

**Issue by SofusGranlund** [TomFrankly/pipedream-notion-voice-notes#98]
Hi,

I’m experiencing an issue with the Summary Language Advanced option in the Pipedream workflow for OpenAI integration. Here’s a detailed explanation of the problem:

	•	When I set the Transcript Language option to Danish (or any other language), the workflow works perfectly, and the transcription is generated without any issues.
	•	However, when I enable Summary Language Advanced and set the summary language to Danish (da) or even English (en), the workflow fails with the following error:

Language detection failed with error: Cannot read properties of undefined (reading 'completions')

Additional Details:
	•	The issue seems isolated to the Summary Language Advanced setting. If this field is left blank, the workflow completes successfully with the default summary language.
	•	I’ve ensured that the OpenAI account is correctly connected, and the API key is working, as the workflow succeeds when Summary Language Advanced is not used.
	•	I have tried both Danish (da) and English (en) as the summary language in the advanced settings, and the error persists regardless of the language.
	•	Debugging shows that the Whisper output is correctly generated, and the transcript data is present before it reaches the ChatGPT step.

It seems like there might be a conflict or issue in how the summary language is being handled when the advanced setting is enabled.

Do you have any insights or recommendations on how to resolve this issue? I’d appreciate any assistance or guidance you can provide.

Thank you for your time and support!

Best regards,
Sofus Granlund

**Comment by TomFrankly** [comment]
Hey @SofusGranlund,

You're correct. The current version does have some issues with translations. I'm working on a new version of this workflow, though I can only do it in my spare time, so I can't provide an estimate as to when it will come out.

**Comment by TomFrankly** [comment]
The best place to keep up to date on this would be our Flylighter Discord, linked here: https://flylighter.com/#pricing

This workflow is not currently part of Flylighter, but a lot of automation discussion happens in that Discord.
